<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThunderPropagator.ClusterMessageBuses.SharedKernel\ThunderPropagator.ClusterMessageBuses.SharedKernel.csproj" />
  </ItemGroup>

</Project>
