<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <IsPackable>false</IsPackable>
      <TargetFramework>net10.0</TargetFramework>
      <TargetFrameworks />
      <EnablePreviewFeatures>true</EnablePreviewFeatures>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NetArchTest.Rules"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.SharedKernel\ThunderPropagator.ClusterMessageBuses.SharedKernel.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.Kafka\ThunderPropagator.ClusterMessageBuses.Kafka.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.RabbitMQ\ThunderPropagator.ClusterMessageBuses.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.NATS\ThunderPropagator.ClusterMessageBuses.NATS.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.Pulsar\ThunderPropagator.ClusterMessageBuses.Pulsar.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.Mqtt\ThunderPropagator.ClusterMessageBuses.Mqtt.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.ActiveMQ\ThunderPropagator.ClusterMessageBuses.ActiveMQ.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.RedisPubSub\ThunderPropagator.ClusterMessageBuses.RedisPubSub.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.WebSocket\ThunderPropagator.ClusterMessageBuses.WebSocket.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.WebApi\ThunderPropagator.ClusterMessageBuses.WebApi.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.TcpSocket\ThunderPropagator.ClusterMessageBuses.TcpSocket.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.UdpClient\ThunderPropagator.ClusterMessageBuses.UdpClient.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.AwsSqs\ThunderPropagator.ClusterMessageBuses.AwsSqs.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.AzureServiceBus\ThunderPropagator.ClusterMessageBuses.AzureServiceBus.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.GcpPubSub\ThunderPropagator.ClusterMessageBuses.GcpPubSub.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.Grpc\ThunderPropagator.ClusterMessageBuses.Grpc.csproj" />
        <ProjectReference Include="..\..\src\ThunderPropagator.ClusterMessageBuses.ZeroMQ\ThunderPropagator.ClusterMessageBuses.ZeroMQ.csproj" />
    </ItemGroup>
</Project>
